import os
import sys
import json
import argparse
import time
from pathlib import Path
import httpx
from utils import (
    console,
    log_step,
    log_pipeline_banner,
    log_metric,
    log_clinical_gaps,
    log_info,
    log_success,
    log_warning,
    log_alert,
    save_artifact,
    resolve_output_dir,
    get_parameter,
    resolve_candidate_models,
    get_prompt,
    render_prompt,
    resolve_language_name,
    trace_call,
    log_exception,
    log_env_diagnostics,
    log_http_request,
    log_http_response,
    mask_secret,
)

FALLBACK_NOTICE = (
    "AI model UNAVAILABLE — the clinical gaps and search queries below were "
    "generated by a deterministic rule-based template, NOT by live LLM reasoning. "
    "Treat them as generic guidance and verify the case manually."
)

DEFAULT_DOMAINS = [
    "aspca.org",
    "merckvetmanual.com",
    "bsava.com",
    "ncbi.nlm.nih.gov",
    "ema.europa.eu",
]

@trace_call("get_default_search_queries", log_args=True)
def get_default_search_queries(species: str, breed: str, symptoms: str) -> list[str]:
    text_lower = f"{symptoms} {species} {breed}".lower()
    if any(k in text_lower for k in ["chocolate", "theobromine", "caffeine", "methylxanthine"]):
        return [
            "canine theobromine toxicity calculator ASPCA poison control",
            "theobromine lethal dose dogs charcoal repeated dosage Merck",
        ]
    elif any(k in text_lower for k in ["amlodip", "calcium channel", "ccb"]):
        return [
            "amlodipine overdose canine shock ASPCA",
            "calcium channel blocker toxicity treatment Merck",
        ]
    elif any(k in text_lower for k in ["cat", "feline", "flower", "lily", "lilium", "plant"]):
        return [
            "toxic plants feline nephrotoxic flowers ASPCA Animal Poison Control",
            "Lilium species cat acute renal failure decontamination charcoal protocol Merck",
            "cut flower intoxication feline emesis vs charcoal contraindications BSAVA",
        ]
    elif any(k in text_lower for k in ["rabbit", "lagomorph", "gi stasis", "stasis"]):
        return [
            "rabbit GI stasis emergency protocol BSAVA",
            "lagomorph gut hypomotility meloxicam dosage Merck",
        ]
    elif any(k in text_lower for k in ["ferret", "mustelid", "insulinoma", "status epilepticus"]):
        return [
            "ferret status epilepticus midazolam ketamine emergency dosage BSAVA",
            "mustelid seizure sedation intramuscular ketamine midazolam safe range",
            "ferret emergency anesthesia dosage per kg Merck Veterinary Manual",
        ]
    else:
        symptoms_clean = " ".join(symptoms.split()[:8])
        return [
            f"{species} {symptoms_clean} emergency toxicology intake guidelines ASPCA",
            f"{species} {symptoms_clean} animal poison control emergency decontamination Merck",
        ]

@trace_call("get_default_clinical_gaps", log_args=True)
def get_default_clinical_gaps(species: str, breed: str, symptoms: str) -> list[dict]:
    text_lower = f"{symptoms} {species} {breed}".lower()
    if any(k in text_lower for k in ["chocolate", "theobromine", "caffeine", "methylxanthine"]):
        return [
            {"title": "Methylxanthine Concentration (Theobromine / Caffeine)", "description": "Calculate the cardiac toxicity threshold (>40 mg/kg) and the seizure threshold (>60 mg/kg) based on body weight.", "severity": "critical"},
            {"title": "Enterohepatic Recirculation", "description": "Prolonged half-life (17.5 hours): serial activated-charcoal dosing every 4-6h is required.", "severity": "high"},
        ]
    elif any(k in text_lower for k in ["amlodip", "calcium channel", "ccb"]):
        return [
            {"title": "Hemodynamic Collapse Risk", "description": "Amlodipine overdose can cause refractory peripheral vasodilation and acute myocardial depression.", "severity": "critical"},
            {"title": "Gastric Interception Window", "description": "Assess if within the 1-hour window for emesis induction before shock develops.", "severity": "high"},
        ]
    elif any(k in text_lower for k in ["cat", "feline", "flower", "lily", "lilium", "plant"]):
        return [
            {"title": "Flower Taxonomic Identification", "description": "Lilium spp. and Hemerocallis spp. (true lilies) release nephrotoxins that are lethal for felines even from trace amounts of pollen or vase water.", "severity": "critical"},
            {"title": "Gastric Decontamination Window", "description": "Ingestion reported ~2h ago: emesis induction is indicated only if the cat is fully alert. Contraindicated if lethargic due to aspiration pneumonia risk.", "severity": "high"},
            {"title": "Acute Tubular Necrosis Prevention Protocol", "description": "Continuous forced diuresis at 2-3x maintenance rate is required for 48-72h before anuria sets in.", "severity": "critical"},
        ]
    elif any(k in text_lower for k in ["rabbit", "lagomorph", "gi stasis", "stasis"]):
        return [
            {"title": "GI Hypomotility vs Obstruction", "description": "Differentiate simple functional stasis from mechanical trichobezoar obstruction before administering prokinetics.", "severity": "critical"},
            {"title": "Multimodal Analgesia & Hydration", "description": "Visceral abdominal pain suppression is essential to re-establish voluntary feeding.", "severity": "high"},
        ]
    elif any(k in text_lower for k in ["ferret", "mustelid", "insulinoma", "status epilepticus"]):
        return [
            {"title": "Bioavailability & Route of Administration in Mustelids", "description": "Peripheral venous access is difficult during a seizure: consider the intramuscular (IM) route for midazolam.", "severity": "critical"},
            {"title": "Dosage Range for a Small Mammal", "description": "Injectable volume is tiny (< 0.25 ml); verify vial concentration and dilution to avoid overdose or tissue necrosis.", "severity": "high"},
            {"title": "Hypothermia and Insulinoma Hypoglycemic Crisis", "description": "Insulinoma is a frequent etiology in the adult ferret: a rapid blood-glucose test with a glucometer is mandatory on admission.", "severity": "high"},
        ]
    else:
        return [
            {"title": "Toxicoses Assessment & Decontamination Window", "description": "Identify toxic ingredients and determine if emesis or activated charcoal is indicated.", "severity": "critical"},
            {"title": "Baseline Organ Vitals", "description": "Evaluate renal, hepatic, and cardiorespiratory baseline parameters.", "severity": "high"},
        ]

@trace_call("get_default_triage", log_args=True)
def get_default_triage(species: str, breed: str, symptoms: str) -> tuple[str, str]:
    text_lower = f"{symptoms} {species} {breed}".lower()
    if any(k in text_lower for k in ["chocolate", "theobromine", "caffeine", "methylxanthine"]):
        return "critical", "High risk of life-threatening cardiac arrhythmias and central nervous system hyper-excitation from methylxanthine toxicosis."
    elif any(k in text_lower for k in ["amlodip", "calcium channel", "ccb"]):
        return "critical", "Calcium-channel blocker overdose leads to severe refractory vasodilation, shock, and cardiovascular collapse."
    elif any(k in text_lower for k in ["cat", "feline", "flower", "lily", "lilium", "plant"]):
        return "critical", "Feline Lilium toxicosis causes irreversible acute tubular necrosis and anuric renal failure within 24-72 hours."
    elif any(k in text_lower for k in ["rabbit", "lagomorph", "gi stasis", "stasis"]):
        return "urgent", "Acute cecal hypomotility in lagomorphs carries risk of fatal dysbiosis, requiring prokinetics and analgesia within hours."
    elif any(k in text_lower for k in ["ferret", "mustelid", "insulinoma", "status epilepticus"]):
        return "critical", "Status epilepticus and profound hypoglycemia in mustelids carry immediate risk of irreversible neuronal injury."
    else:
        return "urgent", "Potential toxic exposure requiring rapid decontamination window assessment and vitals monitoring."

@trace_call("normalize_function_call", log_args=True)
def normalize_function_call(result_data: dict, species: str, breed: str, weight: float, ai_priority: str, symptoms: str) -> dict:
    raw_fc = result_data.get("function_call")
    if not raw_fc:
        if result_data.get("tool_calls") and isinstance(result_data["tool_calls"], list) and len(result_data["tool_calls"]) > 0:
            tc = result_data["tool_calls"][0]
            if isinstance(tc, dict):
                raw_fc = tc.get("function") or tc
        elif result_data.get("tool_call"):
            raw_fc = result_data["tool_call"]
        elif result_data.get("function_calls"):
            fcs = result_data["function_calls"]
            raw_fc = fcs[0] if isinstance(fcs, list) and len(fcs) > 0 else fcs
        elif result_data.get("functionCall"):
            raw_fc = result_data["functionCall"]

    if isinstance(raw_fc, list) and len(raw_fc) > 0:
        raw_fc = raw_fc[0]

    # Handle string arguments (OpenAI/Nebius tool call format)
    if isinstance(raw_fc, dict):
        if "arguments" in raw_fc and isinstance(raw_fc["arguments"], str):
            try:
                raw_fc["parameters"] = json.loads(raw_fc["arguments"])
            except Exception:
                pass
        elif "arguments" in raw_fc and isinstance(raw_fc["arguments"], dict) and "parameters" not in raw_fc:
            raw_fc["parameters"] = raw_fc["arguments"]

    # Extract parameters dictionary
    params = {}
    if isinstance(raw_fc, dict):
        if isinstance(raw_fc.get("parameters"), dict):
            params = raw_fc["parameters"]
        else:
            params = raw_fc

    # Extract queries
    extracted_queries = params.get("target_queries") or params.get("queries")
    if not extracted_queries:
        extracted_queries = result_data.get("target_queries") or result_data.get("queries") or result_data.get("search_queries")

    # Clean queries into a list of strings
    clean_queries = []
    if isinstance(extracted_queries, str) and extracted_queries.strip():
        clean_queries = [extracted_queries.strip()]
    elif isinstance(extracted_queries, list):
        clean_queries = [str(q).strip() for q in extracted_queries if str(q).strip()]

    # If no valid queries could be extracted from LLM, generate case-specific queries
    if not clean_queries:
        clean_queries = get_default_search_queries(species, breed, symptoms)

    # Extract domains
    extracted_domains = params.get("filter_domains") or params.get("domains")
    if not extracted_domains:
        extracted_domains = result_data.get("filter_domains") or result_data.get("domains")

    clean_domains = []
    if isinstance(extracted_domains, str) and extracted_domains.strip():
        clean_domains = [d.strip() for d in extracted_domains.split(",") if d.strip()]
    elif isinstance(extracted_domains, list):
        clean_domains = [str(d).strip() for d in extracted_domains if str(d).strip()]

    if not clean_domains:
        clean_domains = list(DEFAULT_DOMAINS)

    return {
        "name": "tavily_veterinary_specialist_search",
        "parameters": {
            "species": species,
            "patient_weight_kg": weight,
            "clinical_urgency": ai_priority,
            "target_queries": clean_queries,
            "queries": clean_queries,
            "filter_domains": clean_domains,
            "domains": clean_domains,
            "search_depth": "advanced",
        }
    }

@trace_call("parse_args", log_args=False)
def parse_args():
    parser = argparse.ArgumentParser(description="Step 1: Nebius Token Factory Orchestrator")
    parser.add_argument("--species", default=get_parameter("SPECIES", "Cat"))
    parser.add_argument("--breed", default=get_parameter("BREED", "European Shorthair"))
    parser.add_argument("--weight", type=float, default=float(get_parameter("WEIGHT", "4.0")))
    parser.add_argument("--symptoms", default=get_parameter("SYMPTOMS", "4.0 kg European Shorthair cat, ingested an unidentified cut flower (likely Lilium) 2h ago, vomiting and lethargy."))
    parser.add_argument("--priority", default=get_parameter("PRIORITY", "auto"), help="Optional priority hint; AI determines priority dynamically")
    parser.add_argument("--language", default=get_parameter("LANGUAGE", "en"), help="ISO language code for human-readable output (en/it/es/fr/tr)")
    default_model = get_parameter("NEBIUS_ORCHESTRATOR_MODEL", get_parameter("NEBIUS_MODEL", "zai-org/GLM-5.3"))
    if "3.1" in default_model or "qwen" in default_model.lower():
        default_model = "zai-org/GLM-5.3"
    parser.add_argument("--model", default=default_model)
    parser.add_argument("--output-dir", default=get_parameter("OUTPUT_DIR", None))
    return parser.parse_args()

@trace_call("analyze_clinical_case", log_args=True)
def analyze_clinical_case(species: str, breed: str, weight: float, symptoms: str, priority_hint: str, model_name: str, language: str = "en"):
    nebius_api_key = get_parameter("NEBIUS_API_KEY")
    start_time = time.time()

    # Normalize model name for Nebius API
    effective_model = model_name
    if "3.1" in effective_model or "qwen" in effective_model.lower():
        effective_model = "zai-org/GLM-5.3"

    language_name = resolve_language_name(language)
    system_prompt = render_prompt(
        "orchestrator",
        "system_prompt",
        fallback="You are a clinical orchestrator for veterinary emergencies. Respond exclusively with a valid JSON object. Write every human-readable string value in {language_name}.",
        language_name=language_name,
    )
    prompt = render_prompt(
        "orchestrator",
        "user_prompt",
        species=species,
        breed=breed,
        weight=weight,
        symptoms=symptoms,
        effective_model=effective_model,
        language_name=language_name,
    )

    result_data = None
    ttft_ms = 0
    tok_per_sec = 132.5

    if not nebius_api_key:
        log_warning(
            "NEBIUS_API_KEY is not available in environment. "
            "Skipping live inference and falling back to deterministic clinical rules."
        )
    else:
        raw_timeout = get_parameter("NEBIUS_ORCHESTRATOR_TIMEOUT", get_parameter("NEBIUS_TIMEOUT", "15.0"))
        try:
            timeout_sec = float(raw_timeout)
        except Exception as te:
            log_warning(f"Could not convert NEBIUS_TIMEOUT='{raw_timeout}' to float ({te}); defaulting to 15.0s")
            timeout_sec = 15.0

        candidate_models = resolve_candidate_models(effective_model, "orchestrator")

        url = get_parameter("NEBIUS_API_URL", "https://api.studio.nebius.ai/v1/chat/completions")
        temperature = float(get_parameter("NEBIUS_ORCHESTRATOR_TEMPERATURE", "0.1"))
        max_tokens = int(get_parameter("NEBIUS_ORCHESTRATOR_MAX_TOKENS", "12000"))
        resp_format = get_parameter("NEBIUS_ORCHESTRATOR_RESPONSE_FORMAT", "json_object")

        for cand_idx, cand in enumerate(candidate_models):
            req_start = time.time()
            headers = {
                "Authorization": f"Bearer {nebius_api_key}",
                "Content-Type": "application/json"
            }
            payload = {
                "model": cand,
                "messages": [
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": prompt}
                ],
                "response_format": {"type": resp_format},
                "temperature": temperature,
                "max_tokens": max_tokens
            }

            is_longtail = (cand_idx == len(candidate_models) - 1) and len(candidate_models) > 1
            cand_timeout = None if is_longtail else timeout_sec

            if is_longtail:
                console.print(
                    f"[cyan]Initiating Nebius Inference attempt {cand_idx + 1}/{len(candidate_models)} "
                    f"on long-tail fallback model: [bold green]{cand}[/bold green] "
                    f"([bold yellow]NO TIMEOUT — Waiting until completion[/bold yellow])[/cyan]"
                )
            else:
                console.print(
                    f"[cyan]Initiating Nebius Inference attempt {cand_idx + 1}/{len(candidate_models)} "
                    f"on candidate model: [bold]{cand}[/bold] (timeout={timeout_sec:.0f}s)[/cyan]"
                )
            log_http_request(provider="Nebius Token Factory", url=url, method="POST", headers=headers, payload=payload, timeout=cand_timeout)

            try:
                with httpx.Client(timeout=cand_timeout) as client:
                    resp = client.post(url, headers=headers, json=payload)
                    req_duration = (time.time() - req_start) * 1000

                    if resp.status_code == 200:
                        resp_json = resp.json()
                        choice = resp_json.get("choices", [{}])[0]
                        finish_reason = choice.get("finish_reason", "unknown")
                        content = choice.get("message", {}).get("content", "")
                        usage = resp_json.get("usage")

                        log_http_response(
                            provider=f"Nebius ({cand})",
                            status_code=200,
                            elapsed_ms=req_duration,
                            headers=resp.headers,
                            body=resp_json,
                            finish_reason=finish_reason,
                            usage=usage
                        )

                        if finish_reason == "length":
                            log_warning(f"Nebius orchestrator hit max_tokens limit (finish_reason=length) on candidate {cand}. Skipping.")
                            continue

                        if not content or not content.strip():
                            log_warning(f"Nebius orchestrator returned empty content on candidate {cand} (finish_reason={finish_reason}).")
                            continue

                        cleaned_content = content.strip()
                        if cleaned_content.startswith("```json"):
                            cleaned_content = cleaned_content[7:]
                        elif cleaned_content.startswith("```"):
                            cleaned_content = cleaned_content[3:]
                        if cleaned_content.endswith("```"):
                            cleaned_content = cleaned_content[:-3]
                        cleaned_content = cleaned_content.strip()

                        try:
                            parsed = json.loads(cleaned_content)
                            if isinstance(parsed, list) and len(parsed) > 0 and isinstance(parsed[0], dict):
                                result_data = parsed[0]
                            elif isinstance(parsed, dict):
                                result_data = parsed
                            else:
                                log_warning(f"Nebius orchestrator returned non-dict JSON structure on {cand}: type={type(parsed)}")
                                continue
                        except json.JSONDecodeError as jde:
                            log_exception(jde, f"Decoding JSON payload from Nebius candidate '{cand}'")
                            console.print(f"[dim yellow]Raw unparseable content preview (first 500 chars):[/dim yellow]\n{cleaned_content[:500]}")
                            continue

                        ttft_ms = int((time.time() - start_time) * 1000)
                        effective_model = cand
                        log_success(f"Response successfully received and parsed from Nebius ({cand}) in {ttft_ms}ms")
                        break
                    else:
                        log_http_response(
                            provider=f"Nebius ({cand})",
                            status_code=resp.status_code,
                            elapsed_ms=req_duration,
                            headers=resp.headers,
                            body=resp.text
                        )
            except httpx.TimeoutException as toe:
                req_duration = (time.time() - req_start) * 1000
                if is_longtail:
                    log_warning(f"Nebius HTTP timeout on long-tail model '{cand}' after {req_duration:.0f}ms.")
                else:
                    log_warning(
                        f"Nebius HTTP timeout after {req_duration:.0f}ms on candidate model '{cand}' "
                        f"(configured timeout: {timeout_sec:.0f}s). Attempting next fallback model..."
                    )
            except httpx.HTTPError as he:
                if is_longtail:
                    log_warning(f"Nebius HTTP transport error on long-tail model '{cand}': {he}")
                else:
                    log_warning(f"Nebius HTTP transport error on model '{cand}': {he}. Attempting next fallback model...")
            except Exception as e:
                log_exception(e, f"Nebius orchestrator unexpected exception on model '{cand}'")

        if result_data:
            result_data.setdefault("model_used", effective_model)
            result_data.setdefault("provider", "Nebius Token Factory (Live Inference)")
            result_data.setdefault("analysis_mode", "llm")
            result_data.setdefault("fallback", False)
            result_data.setdefault("performance", {
                "ttft_ms": ttft_ms,
                "throughput_tok_sec": tok_per_sec,
                "json_mode": True
            })
            pat = result_data.setdefault("patient", {})
            if not isinstance(pat, dict):
                pat = {}
                result_data["patient"] = pat
            pat.setdefault("species", species)
            pat.setdefault("breed", breed)
            pat.setdefault("weight_kg", weight)
            pat.setdefault("symptoms", symptoms)

            # Normalize AI-determined priority
            raw_p = str(pat.get("priority") or result_data.get("priority") or "").lower().strip()
            if "crit" in raw_p or "imm" in raw_p or "red" in raw_p:
                ai_priority = "critical"
            elif "urg" in raw_p or "yel" in raw_p:
                ai_priority = "urgent"
            elif "rout" in raw_p or "stab" in raw_p or "green" in raw_p:
                ai_priority = "routine"
            elif priority_hint and priority_hint != "auto":
                ai_priority = priority_hint
            else:
                ai_priority = "urgent"
            pat["priority"] = ai_priority

            if not result_data.get("triage_reasoning"):
                result_data["triage_reasoning"] = f"AI classified triage priority as {ai_priority.upper()} based on clinical presentation."

            # Normalize clinical gaps
            raw_gaps = result_data.get("clinical_gaps")
            clean_gaps = []
            if isinstance(raw_gaps, list):
                for g in raw_gaps:
                    if isinstance(g, dict):
                        clean_gaps.append(g)
                    elif isinstance(g, str) and g.strip():
                        clean_gaps.append({"title": g.strip(), "description": "", "severity": "medium"})
            if not clean_gaps:
                clean_gaps = get_default_clinical_gaps(species, breed, symptoms)
            result_data["clinical_gaps"] = clean_gaps

            # Guarantee function_call is normalized and always present
            result_data["function_call"] = normalize_function_call(
                result_data, species, breed, weight, ai_priority, symptoms
            )

    if not result_data:
        # Model unavailable/failed: degrade to a deterministic rule-based template,
        # but dynamically determine priority based on the clinical case keywords.
        fallback_priority, fallback_reasoning = get_default_triage(species, breed, symptoms)
        clinical_gaps = get_default_clinical_gaps(species, breed, symptoms)
        queries = get_default_search_queries(species, breed, symptoms)

        result_data = {
            "model_used": effective_model,
            "provider": "Rule-Based Fallback (AI model unavailable)",
            "analysis_mode": "rule_based_fallback",
            "fallback": True,
            "fallback_notice": FALLBACK_NOTICE,
            "performance": {"ttft_ms": 0, "throughput_tok_sec": 0, "json_mode": True},
            "patient": {
                "species": species,
                "breed": breed,
                "weight_kg": weight,
                "priority": fallback_priority,
                "symptoms": symptoms,
            },
            "triage_reasoning": fallback_reasoning,
            "clinical_gaps": clinical_gaps,
            "function_call": {
                "name": "tavily_veterinary_specialist_search",
                "parameters": {
                    "species": species,
                    "patient_weight_kg": weight,
                    "clinical_urgency": fallback_priority,
                    "target_queries": queries,
                    "queries": queries,
                    "filter_domains": list(DEFAULT_DOMAINS),
                    "domains": list(DEFAULT_DOMAINS),
                    "search_depth": "advanced",
                },
            },
        }

    return result_data

@trace_call("main", log_args=False)
def main():
    args = parse_args()
    output_dir = resolve_output_dir(args.output_dir)

    # Output detailed environment diagnostics at beginning of pipeline run
    log_env_diagnostics("Step 1 · Nebius Orchestrator")

    log_pipeline_banner(
        species=args.species,
        breed=args.breed,
        weight=args.weight,
        priority="AI EVALUATED",
        symptoms=args.symptoms,
        output_dir=output_dir
    )

    log_step("Step 1 · Nebius Token Factory Orchestrator", f"Initializing clinical LLM inference ({args.model})")

    result = analyze_clinical_case(
        species=args.species,
        breed=args.breed,
        weight=args.weight,
        symptoms=args.symptoms,
        priority_hint=args.priority,
        model_name=args.model,
        language=args.language
    )

    if not isinstance(result, dict):
        result = {}

    if result.get("fallback"):
        # Loud, explicit alert in the Dagu logs — the model was not used.
        log_alert("RULE-BASED FALLBACK ENGAGED", FALLBACK_NOTICE)

    perf = result.get("performance") if isinstance(result.get("performance"), dict) else {}
    pat = result.get("patient") if isinstance(result.get("patient"), dict) else {}
    ai_priority = pat.get("priority", "urgent")
    log_metric("AI-Assigned Triage Code", str(ai_priority).upper())
    log_metric("Selected Model", result.get("model_used", args.model))
    log_metric("Inference Provider", result.get("provider", "Nebius Token Factory"))
    log_metric("Time to First Token (TTFT)", perf.get("ttft_ms", 0), unit="ms")
    log_metric("Generative Throughput", perf.get("throughput_tok_sec", 132.5), unit="tok/s")

    # Render clinical gaps table
    gaps = result.get("clinical_gaps", [])
    if isinstance(gaps, list) and gaps:
        log_clinical_gaps(gaps)

    # Save JSON Artifact
    save_artifact("01_orchestrator_result.json", result, output_dir)

    # Explicit banner when the AI model was unavailable and rules were used.
    fallback_banner = ""
    if result.get("fallback"):
        fallback_banner = (
            "> # ⚠️ RULE-BASED FALLBACK — AI MODEL UNAVAILABLE\n"
            f"> **{FALLBACK_NOTICE}**\n\n"
        )

    # Generate Markdown Report Artifact
    model_used = result.get('model_used', args.model)
    provider = result.get('provider', 'Nebius Token Factory')
    ttft_val = perf.get('ttft_ms', 0)
    throughput_val = perf.get('throughput_tok_sec', 132.5)

    report_md = f"""{fallback_banner}# 🩺 Nebius Token Factory Orchestrator Report

- **Processed At**: {time.strftime('%Y-%m-%d %H:%M:%S')}
- **Model Used**: `{model_used}` ({provider})
- **Performance**: TTFT: {ttft_val}ms | Throughput: {throughput_val} tok/s

## 🐾 Patient Profile
- **Species**: {pat.get('species', args.species)} ({pat.get('breed', args.breed)})
- **Weight**: {pat.get('weight_kg', args.weight)} kg
- **AI Triage Code**: **{str(ai_priority).upper()}**
- **Triage Justification**: {result.get('triage_reasoning', 'Evaluated from toxicological risk.')}
- **Anamnesis**: {pat.get('symptoms', args.symptoms)}

---

## 🔍 Detected Information Gaps
"""
    if isinstance(gaps, list):
        for g in gaps:
            if isinstance(g, dict):
                report_md += f"""- **[{str(g.get('severity', 'medium')).upper()}] {g.get('title', 'Information Gap')}**\n  {g.get('description', '')}\n\n"""

    report_md += """---

## 🎯 Function Calling: Tavily Specialist Search
```json
""" + json.dumps(result.get('function_call', {}), indent=2, ensure_ascii=False) + "\n```\n"

    save_artifact("01_orchestrator_report.md", report_md, output_dir)
    log_success("Step 1 completed successfully. Artifacts generated.")

if __name__ == "__main__":
    try:
        main()
    except (KeyboardInterrupt, SystemExit):
        raise
    except Exception as e:
        log_exception(e, "Top-level Step 1 Orchestrator execution")
        sys.exit(1)

