import os
import sys
import json
import argparse
import re
import time
from pathlib import Path
import httpx
from utils import (
    console,
    log_step,
    log_metric,
    log_dosage_table,
    log_info,
    log_success,
    log_warning,
    log_alert,
    save_artifact,
    generate_run_index,
    get_central_artifacts_dir,
    resolve_output_dir,
    get_parameter,
    resolve_candidate_models,
    get_prompt,
    render_prompt,
    resolve_language_name,
    trace_call,
    log_exception,
    log_http_request,
    log_http_response,
    mask_secret,
)

FALLBACK_NOTICE = (
    "AI model UNAVAILABLE — this protocol was generated by the deterministic "
    "rule-based formula, NOT by evidence-grounded LLM synthesis. Doses are "
    "template-based: a clinician MUST manually verify every value before use."
)

@trace_call("parse_args", log_args=False)
def parse_args():
    parser = argparse.ArgumentParser(description="Step 3: Nebius Clinical Synthesis & Dosage Calculation")
    parser.add_argument("--output-dir", default=get_parameter("OUTPUT_DIR", None))
    parser.add_argument("--language", default=get_parameter("LANGUAGE", "en"), help="ISO language code for human-readable output (en/it/es/fr/tr)")
    return parser.parse_args()

@trace_call("classify_case", log_args=True, log_result=True)
def classify_case(text: str) -> str:
    """Selects the clinical branch that best matches the intake (English keywords)."""
    t = text.lower()
    if any(k in t for k in ["amlodip", "calcium channel", "calcium-channel", "blister", "ccb"]):
        return "amlodipine"
    if any(k in t for k in ["rabbit", "lagomorph", "gi stasis", "stasis", "cecal", "anorexia"]):
        return "rabbit"
    if any(k in t for k in ["lameness", "tick", "lyme", "borrelia", "anaplasma", "vector-borne"]):
        return "tick"
    if any(k in t for k in ["cat", "feline", "lily", "lilium", "cut flower", "flower"]):
        return "lily"
    if any(k in t for k in ["ferret", "mustelid", "status epilepticus", "seizure", "convuls"]):
        return "ferret"
    return "chocolate"

@trace_call("build_clinical_synthesis", log_args=True)
def build_clinical_synthesis(patient: dict, documents: list[dict]):
    species = patient.get("species", "Cat")
    weight = float(patient.get("weight_kg", 4.0))
    symptoms = patient.get("symptoms", "")
    breed = patient.get("breed", "")

    case = classify_case(f"{symptoms} {species} {breed}")

    if case == "amlodipine":
        pills_max = 6
        mg_total = pills_max * 10
        dose_per_kg = mg_total / weight
        apomorphine_mg = weight * 0.035
        apomorphine_ml = (weight * 0.035) / 10
        calcium_ml = weight * 1.0
        diagnosis = f"Massive Calcium-Channel Blocker Overdose (Amlodipine: {dose_per_kg:.2f} mg/kg - Shock Risk)"
        immediate_protocol = {
            "emesis_induction": {
                "indication": "YES (Immediate emesis if < 1 hour)",
                "details": f"Ingestion within the last hour: induce emesis immediately with Apomorphine to intercept the slow-release tablets. Dose for {weight} kg: {apomorphine_mg:.2f} mg ({apomorphine_ml:.3f} ml) rapid IV. Contraindicated once hypotension or reduced consciousness develops."
            },
            "activated_charcoal": {
                "indication": "YES (Single or repeated dose)",
                "details": f"Aqueous activated charcoal 1-2 g/kg ({(weight * 1.5):.0f} grams) after emesis to adsorb the residual fraction of amlodipine in the gastrointestinal tract."
            },
            "specific_antidote": {
                "indication": "Hemodynamic Support (Calcium Gluconate / Vasopressors / ILE)",
                "details": f"Ingested dose ({dose_per_kg:.2f} mg/kg) is over 2x the critical threshold (>1.0 mg/kg): expect severe peripheral vasodilation and blood-pressure collapse. Avoid large crystalloid boluses (pulmonary edema risk). Give slow IV Calcium Gluconate 10%, a Norepinephrine infusion, and Intravenous Lipid Emulsion (ILE 20%) as rescue."
            }
        }
        dosage_table = [
            {"drug": "Apomorphine HCl (Emetic)", "standard_dosage": "0.03 - 0.04 mg/kg", "patient_dose": f"{apomorphine_mg:.2f} mg ({apomorphine_ml:.3f} ml)", "route": "IV / Subconjunctival", "formulation": "10 mg/ml vial", "monitoring": "Rapid emesis in 2-5 min. Reversible with Naloxone 0.04 mg/kg IV."},
            {"drug": "Calcium Gluconate 10% (Ca2+ inotrope)", "standard_dosage": "0.5 - 1.5 ml/kg", "patient_dose": f"{calcium_ml:.1f} ml slow", "route": "Very slow IV (over 15-20 min)", "formulation": "10% solution (100 mg/ml)", "monitoring": "Under strict continuous ECG monitoring (stop infusion on bradycardia or QT prolongation)."},
            {"drug": "Activated Charcoal (Aqueous slurry)", "standard_dosage": "1.0 - 2.0 g/kg", "patient_dose": f"{(weight * 1.5):.0f} grams", "route": "PO", "formulation": "10% suspension", "monitoring": "Give after gastric decontamination is complete. Protect the airway."},
            {"drug": "Norepinephrine / ILE 20% (Shock rescue)", "standard_dosage": "0.1 - 2.0 mcg/kg/min", "patient_dose": "Continuous IV titration", "route": "CRI / IV bag", "formulation": "Syringe pump", "monitoring": "Alpha-1 vasopressor to counter vasodilation and keep MAP > 65 mmHg."}
        ]
        sources = [
            {"id": "[1]", "source": "ASPCA Animal Poison Control Center", "title": "Amlodipine Besylate Toxicosis in Canines: Emergency Management Guidelines", "url": "https://www.aspca.org"},
            {"id": "[2]", "source": "Merck Veterinary Manual", "title": "Calcium Channel Blocker Poisoning & Hemodynamic Stabilization Protocols", "url": "https://www.merckvetmanual.com"},
            {"id": "[3]", "source": "BSAVA Small Animal Formulary", "title": "Emergency Antidotes, Vasopressors and Lipid Emulsion Therapy in Dogs", "url": "https://www.bsava.com"}
        ]

    elif case == "rabbit":
        meloxicam_mg = weight * 0.75
        meloxicam_ml = (weight * 0.75) / 5
        metoclopramide_mg = weight * 0.5
        metoclopramide_ml = (weight * 0.5) / 5
        fluid_day = weight * 80
        diagnosis = "Rabbit Gastrointestinal Stasis Syndrome (RGIS - Orphan Species)"
        immediate_protocol = {
            "emesis_induction": {
                "indication": "NO (Anatomically impossible)",
                "details": "Rabbits cannot vomit due to an extremely tonic cardiac sphincter and the absence of a vomiting center. Emesis attempts are contraindicated."
            },
            "activated_charcoal": {
                "indication": "NO (Not indicated in functional stasis)",
                "details": "Dysmotility disorder with dehydration of the cecal food mass; activated charcoal would worsen the gastric impaction."
            },
            "specific_antidote": {
                "indication": "Multimodal Motility & Analgesia Therapy (NO toxic antibiotics)",
                "details": "Strictly FORBIDDEN: penicillins, ampicillin, cephalosporins and macrolides (they cause lethal Clostridium enterotoxemia). Cornerstone protocol: high-dose Meloxicam (0.5-1.0 mg/kg), prokinetics (Metoclopramide/Cisapride) and rehydration of the cecal mass."
            }
        }
        dosage_table = [
            {"drug": "Meloxicam (NSAID analgesic for rabbits)", "standard_dosage": "0.5 - 1.0 mg/kg", "patient_dose": f"{meloxicam_mg:.2f} mg ({meloxicam_ml:.2f} ml)", "route": "SC / PO q12-24h", "formulation": "5 mg/ml injectable vial", "monitoring": "Rabbits require doses 4x higher than dogs due to high hepatic clearance. Key to breaking the pain-stasis cycle."},
            {"drug": "Metoclopramide HCl (Prokinetic)", "standard_dosage": "0.5 mg/kg", "patient_dose": f"{metoclopramide_mg:.2f} mg ({metoclopramide_ml:.2f} ml)", "route": "SC / PO q8h", "formulation": "5 mg/ml vial", "monitoring": "Stimulates gastric and duodenal motility. First rule out mechanical obstruction."},
            {"drug": "Pre-warmed Lactated Ringer's (Fluid therapy)", "standard_dosage": "75 - 100 ml/kg/day", "patient_dose": f"{fluid_day:.0f} ml/day (split SC or IV)", "route": "SC / Continuous IV", "formulation": "500 ml bag", "monitoring": "Rehydrates the cecal contents and softens the trichobezoar."},
            {"drug": "Critical Care / Oxbow (Assisted feeding)", "standard_dosage": "10 - 15 ml/kg q6-8h", "patient_dose": f"{(weight * 12):.0f} ml slurry per meal", "route": "PO via syringe", "formulation": "Warm rehydrated powder", "monitoring": "Crude fiber (>25%) essential to restart cecal fermentation and prevent hepatic lipidosis."}
        ]
        sources = [
            {"id": "[1]", "source": "BSAVA Exotic Pets Formulary", "title": "Lagomorph Emergency Analgesia and Gastrointestinal Motility Guidelines", "url": "https://www.bsava.com"},
            {"id": "[2]", "source": "Exotic Animal Formulary (Carpenter & Marion)", "title": "Rabbit Gastrointestinal Syndrome & Antibiotic Enterotoxemia Prevention", "url": "https://www.merckvetmanual.com"},
            {"id": "[3]", "source": "PubMed / Journal of Exotic Pet Medicine", "title": "Pharmacokinetics and Clinical Efficacy of High-Dose Meloxicam in Domestic Rabbits", "url": "https://pubmed.ncbi.nlm.nih.gov"}
        ]

    elif case == "tick":
        doxy_day = weight * 10
        doxy_half = weight * 5
        diagnosis = "Tick-Borne Vector Infection (Borrelia vs Anaplasma) & Polyarthritis"
        immediate_protocol = {
            "emesis_induction": {
                "indication": "NO (Systemic infectious disease)",
                "details": "Systemic infectious/immunological picture not arising from acute toxin ingestion."
            },
            "activated_charcoal": {
                "indication": "NO (Not applicable)",
                "details": "No intraluminal toxin to adsorb."
            },
            "specific_antidote": {
                "indication": "Targeted Antimicrobial Therapy & Rapid Serological Test",
                "details": "First-line treatment targeted against spirochetes (Borrelia burgdorferi) and intracellular bacteria (Anaplasma phagocytophilum / Ehrlichia canis). Mandatory warning: give Doxycycline strictly with food or followed by plenty of water to avoid erosive esophagitis."
            }
        }
        dosage_table = [
            {"drug": "Doxycycline (First-line antimicrobial)", "standard_dosage": "10 mg/kg/day (split q12h)", "patient_dose": f"{doxy_day:.0f} mg/day ({doxy_half:.0f} mg every 12h)", "route": "PO with a full meal", "formulation": "100 mg / 200 mg tablets", "monitoring": "MANDATORY with a meal or plenty of water to prevent caustic esophageal stricture. Duration: 28 days."},
            {"drug": "Meloxicam (Joint anti-inflammatory NSAID)", "standard_dosage": "0.2 mg/kg day 1, then 0.1 mg/kg", "patient_dose": f"{(weight * 0.2):.1f} mg day 1, then {(weight * 0.1):.1f} mg/day", "route": "PO / SC", "formulation": "Oral suspension 1.5 mg/ml", "monitoring": "Relieves joint tenderness and fever in the first 48h while awaiting the antibiotic effect."},
            {"drug": "SNAP 4Dx Plus In-Clinic Test", "standard_dosage": "3 drops whole blood / serum", "patient_dose": "1 Test Kit", "route": "Rapid in-clinic ELISA", "formulation": "Result in 8 minutes", "monitoring": "Detects Borrelia (C6), Anaplasma, Ehrlichia canis antibodies and Dirofilaria antigen."}
        ]
        sources = [
            {"id": "[1]", "source": "ASPCA / CDC Vector-Borne Panel", "title": "Canine Lyme Disease & Anaplasmosis Diagnostic and Treatment Consensus", "url": "https://www.aspca.org"},
            {"id": "[2]", "source": "Merck Veterinary Manual", "title": "Tick-Borne Polyarthritis in Canines: Pathophysiology and Differential Diagnosis", "url": "https://www.merckvetmanual.com"},
            {"id": "[3]", "source": "BSAVA Small Animal Formulary", "title": "Doxycycline Clinical Practice Guidelines & Esophageal Safety Protocols", "url": "https://www.bsava.com"}
        ]

    elif case == "lily":
        fluid_hour = weight * 7.0
        fluid_day = weight * 7.0 * 24
        diagnosis = "Acute Nephrotoxicosis from a Cut Plant (Easter Lily / Lilium spp.)"
        immediate_protocol = {
            "emesis_induction": {
                "indication": "YES (Only if alert & < 2-4 hours)",
                "details": "Emesis induction only if the patient is alert within 2-4 hours. Use EXCLUSIVELY Dexmedetomidine (10-20 mcg/kg IM, reversible with Atipamezole). NEVER use apomorphine in cats."
            },
            "activated_charcoal": {
                "indication": "YES (Aqueous slurry 1-2 g/kg)",
                "details": "1.0 - 2.0 g/kg PO first dose with sorbitol; subsequent doses every 6-8 hours without sorbitol to adsorb luminal toxins and prevent reabsorption."
            },
            "specific_antidote": {
                "indication": "Life-Saving Continuous IV Forced Diuresis (Target < 18h)",
                "details": f"No specific antidote exists. Life-saving therapy: continuous infusion of isotonic crystalloids (Lactated Ringer's) at 7.0 ml/kg/h ({fluid_hour:.1f} ml/h for {weight} kg) uninterrupted for 48-72 hours before terminal anuria."
            }
        }
        dosage_table = [
            {"drug": "Lactated Ringer's (Intensive forced fluid therapy)", "standard_dosage": "6.0 - 8.0 ml/kg/h", "patient_dose": f"{fluid_hour:.1f} ml/h ({fluid_day:.0f} ml/day)", "route": "Continuous IV (forced diuresis)", "formulation": "500 / 1000 ml bag", "monitoring": "Start within 18 hours. Monitor hourly urine output (target > 1.5-2.0 ml/kg/h)."},
            {"drug": "Activated Charcoal (Aqueous suspension)", "standard_dosage": "1.0 - 2.0 g/kg", "patient_dose": f"{(weight * 1.5):.1f} grams", "route": "PO (diluted slurry via oral syringe or tube)", "formulation": "100 mg/ml (10% suspension)", "monitoring": "Dilute in 15 ml of water. Scrupulously protect the airway."},
            {"drug": "Maropitant (Cerenia)", "standard_dosage": "1.0 mg/kg", "patient_dose": f"{(weight * 1.0):.1f} mg ({((weight * 1.0) / 10):.2f} ml)", "route": "SC / slow IV", "formulation": "10 mg/ml vial", "monitoring": "NK-1 anti-emetic q24h post-decontamination to stop fluid loss from vomiting."}
        ]
        sources = [
            {"id": "[1]", "source": "ASPCA Animal Poison Control Center", "title": "Lily Toxicosis in Domestic Felines: Glucuronyltransferase Deficiency & Renal Pathology", "url": "https://www.aspca.org"},
            {"id": "[2]", "source": "Merck Veterinary Manual", "title": "Critical Care Protocol: Acute Renal Failure Prevention in Feline Lily Exposure", "url": "https://www.merckvetmanual.com"},
            {"id": "[3]", "source": "BSAVA Small Animal Formulary", "title": "Emergency Feline Decontamination and Crystalloid Diuresis Targets", "url": "https://www.bsava.com"}
        ]

    elif case == "ferret":
        midazolam_mg = weight * 0.75
        midazolam_ml = (weight * 0.75) / 5.0
        ketamine_mg = weight * 6.0
        ketamine_ml = (weight * 6.0) / 100.0
        diagnosis = "Refractory Status Epilepticus / Neurological Crisis in Mustelids"
        immediate_protocol = {
            "emesis_induction": {
                "indication": "NO (Absolutely contraindicated)",
                "details": "Fatal aspiration risk in a patient with altered consciousness or active seizure."
            },
            "activated_charcoal": {
                "indication": "NOT APPLICABLE",
                "details": "Not indicated for acute neurological emergencies and status epilepticus."
            },
            "specific_antidote": {
                "indication": "Midazolam + Ketamine (Emergency anesthetic protocol)",
                "details": "Midazolam is the fast first-line choice IM/IN. For refractory seizures, Ketamine IM provides NMDA-receptor blockade. Check blood glucose immediately to rule out insulinoma."
            }
        }
        dosage_table = [
            {"drug": "Midazolam", "standard_dosage": "0.5 - 1.0 mg/kg", "patient_dose": f"{midazolam_mg:.2f} mg ({midazolam_ml:.2f} ml)", "route": "IM / IN (rapid mucosal administration)", "formulation": "5 mg/ml vial", "monitoring": "Use an insulin syringe. Monitor airway patency and respiratory rate."},
            {"drug": "Ketamine (dissociative anesthetic)", "standard_dosage": "5.0 - 10.0 mg/kg", "patient_dose": f"{ketamine_mg:.1f} mg ({ketamine_ml:.2f} ml)", "route": "IM (second-line rescue)", "formulation": "100 mg/ml vial", "monitoring": "Second line for prolonged seizures (>10 minutes)."},
            {"drug": "Glucose 50% (Rapid bolus)", "standard_dosage": "0.5 - 1.0 ml/kg (diluted 1:1)", "patient_dose": f"{(weight * 0.75):.2f} ml diluted", "route": "Slow IV / Buccal (dilute 1:1 with saline)", "formulation": "50% vial with saline", "monitoring": "Immediate glucometer check to exclude insulinoma."}
        ]
        sources = [
            {"id": "[1]", "source": "BSAVA Exotic Pets Formulary", "title": "Emergency Anticonvulsant Protocols in Mustelids (Mustela putorius furo)", "url": "https://www.bsava.com"},
            {"id": "[2]", "source": "Merck Veterinary Manual (Exotic Animals)", "title": "Emergency Care & Critical Anesthesia in Ferrets", "url": "https://www.merckvetmanual.com"}
        ]

    else:
        match = re.search(r"(\d+)\s*g", symptoms.lower())
        grams = float(match.group(1)) if match else 150.0
        conc_mg_g = 16.0
        dose_per_kg = (grams * conc_mg_g) / weight
        apomorphine_mg = weight * 0.035
        apomorphine_ml = (weight * 0.035) / 10
        diagnosis = f"Acute Theobromine Poisoning (Dark Bitter Chocolate: {dose_per_kg:.1f} mg/kg - Critical Risk)"
        immediate_protocol = {
            "emesis_induction": {
                "indication": "YES (Emesis recommended within 2 hours)",
                "details": f"Recent ingestion (< 2 hours) and patient alert: induce emesis immediately with Apomorphine. Dose for {weight} kg: {apomorphine_mg:.2f} mg ({apomorphine_ml:.3f} ml) IV or subconjunctival."
            },
            "activated_charcoal": {
                "indication": "YES (Serial doses every 4-6h)",
                "details": "1.0 - 2.0 g/kg PO first dose with a cathartic after emesis stops, then 0.5 g/kg without a cathartic every 4-6 hours for 24h due to prolonged enterohepatic recirculation (half-life 17.5h)."
            },
            "specific_antidote": {
                "indication": "ECG Monitoring & Intensive Fluid Therapy",
                "details": f"Ingested dose ({dose_per_kg:.1f} mg/kg) exceeds the critical threshold (>60 mg/kg): high risk of ventricular tachyarrhythmias and seizures. Continuous ECG, urinary catheter and diuresis fluids (4-6 ml/kg/h). If severe tachycardia: Propranolol 0.02-0.06 mg/kg slow IV."
            }
        }
        dosage_table = [
            {"drug": "Apomorphine HCl (Emetic of choice)", "standard_dosage": "0.03 - 0.04 mg/kg", "patient_dose": f"{apomorphine_mg:.2f} mg ({apomorphine_ml:.3f} ml)", "route": "Rapid IV (or subconjunctival)", "formulation": "10 mg/ml vial", "monitoring": "Rapid emesis in 2-5 min. Reversible with Naloxone (0.04 mg/kg IV)."},
            {"drug": "Lactated Ringer's / NaCl 0.9% (Intensive fluid therapy)", "standard_dosage": "4.0 - 6.0 ml/kg/h", "patient_dose": f"{(weight * 5.0):.1f} ml/h ({(weight * 5.0 * 24):.0f} ml/day)", "route": "Continuous IV (volume expansion & diuresis)", "formulation": "1000 ml IV bag", "monitoring": "Volume expansion, accelerated renal clearance of theobromine and cardiovascular support."},
            {"drug": "Activated Charcoal (Aqueous suspension)", "standard_dosage": "1.0 - 2.0 g/kg", "patient_dose": f"{(weight * 1.5):.0f} grams", "route": "PO (give slurry after emesis)", "formulation": "10% suspension (100 mg/ml)", "monitoring": "Give after emesis. Repeat at 0.5 g/kg q4-6h for 24h to intercept enterohepatic recirculation."},
            {"drug": "Propranolol HCl (Beta-blocker anti-arrhythmic)", "standard_dosage": "0.02 - 0.06 mg/kg", "patient_dose": f"{(weight * 0.03):.2f} mg", "route": "Slow IV (infuse over 3-5 min under ECG)", "formulation": "1 mg/ml vial", "monitoring": "Under constant ECG guidance if heart rate exceeds 180 bpm or VPCs appear."}
        ]
        sources = [
            {"id": "[1]", "source": "ASPCA Animal Poison Control Center", "title": "Theobromine Toxicity Profile: Purity Correlation & Canine Exposure Thresholds", "url": "https://www.aspca.org"},
            {"id": "[2]", "source": "Merck Veterinary Manual", "title": "Chocolate and Methylxanthine Intoxication in Canines: Emergency Management", "url": "https://www.merckvetmanual.com"},
            {"id": "[3]", "source": "BSAVA Small Animal Formulary", "title": "Apomorphine Emesis Protocol and Critical Cardiac Monitoring in Small Animals", "url": "https://www.bsava.com"}
        ]

    return {
        "timestamp": time.strftime('%Y-%m-%d %H:%M:%S'),
        "patient": patient,
        "presumptive_diagnosis": diagnosis,
        "immediate_intervention_protocol": immediate_protocol,
        "dosage_calculation_table": dosage_table,
        "mandatory_sources": sources
    }

@trace_call("_valid_synthesis", log_args=False, log_result=True)
def _valid_synthesis(data):
    """Minimal structural validation of an LLM-produced synthesis object with detailed diagnostic logging."""
    if not isinstance(data, dict):
        log_warning(f"Validation rejected: response is not a dict (got {type(data).__name__})")
        return False
    if not data.get("presumptive_diagnosis"):
        log_warning("Validation rejected: missing 'presumptive_diagnosis' key or value is empty")
        return False
    proto = data.get("immediate_intervention_protocol")
    if not isinstance(proto, dict):
        log_warning(f"Validation rejected: 'immediate_intervention_protocol' is not a dict (got {type(proto).__name__})")
        return False
    required_proto_keys = {"emesis_induction", "activated_charcoal", "specific_antidote"}
    missing_proto = required_proto_keys - set(proto.keys())
    if missing_proto:
        log_warning(f"Validation rejected: 'immediate_intervention_protocol' is missing mandatory keys: {missing_proto}")
        return False
    table = data.get("dosage_calculation_table")
    if not isinstance(table, list) or not table:
        log_warning(f"Validation rejected: 'dosage_calculation_table' must be a non-empty list (got {type(table).__name__}, len={len(table) if isinstance(table, list) else 'N/A'})")
        return False
    return True

@trace_call("synthesize_with_llm", log_args=True)
def synthesize_with_llm(patient, documents, model_name, language: str = "en"):
    """Evidence-grounded synthesis: feeds the retrieved documents back into the
    Nebius LLM to produce the protocol. Returns None if unavailable/invalid so
    the caller can fall back to the deterministic clinical rules."""
    api_key = get_parameter("NEBIUS_API_KEY")
    if not api_key:
        log_warning("NEBIUS_API_KEY is not configured or resolved. Cannot perform live synthesis inference; using deterministic rules.")
        return None
    if not documents:
        log_warning("No clinical search documents provided from Step 2. Cannot ground synthesis; using deterministic rules.")
        return None

    weight = float(patient.get("weight_kg", 4.0))
    evidence = "\n\n".join(
        f"[{i + 1}] {d.get('source_name') or d.get('source_domain', 'source')} — {d.get('title', '')}\n"
        f"URL: {d.get('url', '')}\n"
        f"{(d.get('cleaned_markdown') or d.get('content', ''))[:1200]}"
        for i, d in enumerate(documents[:6])
    )

    language_name = resolve_language_name(language)
    system_prompt = render_prompt(
        "clinical_synthesis",
        "system_prompt",
        fallback="You are a veterinary clinical synthesis engine. Respond only with a valid JSON object, grounded in the provided evidence. Write every human-readable prose value in {language_name}.",
        language_name=language_name,
    )
    prompt = render_prompt(
        "clinical_synthesis",
        "user_prompt",
        species=patient.get("species"),
        breed=patient.get("breed"),
        weight=weight,
        priority=patient.get("priority"),
        symptoms=patient.get("symptoms"),
        evidence=evidence,
        language_name=language_name,
    )

    synthesis_model = get_parameter("NEBIUS_SYNTHESIS_MODEL", get_parameter("NEBIUS_MODEL", "zai-org/GLM-5.3"))
    raw_timeout = get_parameter("NEBIUS_SYNTHESIS_TIMEOUT", get_parameter("NEBIUS_TIMEOUT", "60.0"))
    try:
        timeout_sec = float(raw_timeout)
    except Exception as te:
        log_warning(f"Could not convert timeout '{raw_timeout}' to float ({te}), using 60.0s")
        timeout_sec = 60.0

    candidate_models = resolve_candidate_models(synthesis_model, "synthesis")
    url = get_parameter("NEBIUS_API_URL", "https://api.studio.nebius.ai/v1/chat/completions")
    temperature = float(get_parameter("NEBIUS_SYNTHESIS_TEMPERATURE", "0.1"))
    max_tokens = int(get_parameter("NEBIUS_SYNTHESIS_MAX_TOKENS", "80000"))
    resp_format = get_parameter("NEBIUS_SYNTHESIS_RESPONSE_FORMAT", "json_object")

    for cand_idx, cand in enumerate(candidate_models):
        req_start = time.time()
        headers = {"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"}
        payload = {
            "model": cand,
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": prompt},
            ],
            "response_format": {"type": resp_format},
            "temperature": temperature,
            "max_tokens": max_tokens,
        }

        is_longtail = (cand_idx == len(candidate_models) - 1) and len(candidate_models) > 1
        cand_timeout = None if is_longtail else timeout_sec

        if is_longtail:
            console.print(
                f"[cyan]Initiating Nebius Clinical Synthesis attempt {cand_idx + 1}/{len(candidate_models)} "
                f"on long-tail fallback model: [bold green]{cand}[/bold green] "
                f"([bold yellow]NO TIMEOUT — Waiting until completion[/bold yellow])...[/cyan]"
            )
        else:
            console.print(
                f"[cyan]Initiating Nebius Clinical Synthesis attempt {cand_idx + 1}/{len(candidate_models)} "
                f"on [bold]{cand}[/bold] (timeout={int(timeout_sec)}s)...[/cyan]"
            )
        log_http_request(provider="Nebius Synthesis", url=url, method="POST", headers=headers, payload=payload, timeout=cand_timeout)

        try:
            with httpx.Client(timeout=cand_timeout) as client:
                resp = client.post(url, headers=headers, json=payload)
                req_duration = (time.time() - req_start) * 1000

                if resp.status_code == 200:
                    resp_json = resp.json()
                    choice = resp_json.get("choices", [{}])[0]
                    finish_reason = choice.get("finish_reason", "unknown")
                    content = choice.get("message", {}).get("content", "")
                    usage = resp_json.get("usage")

                    log_http_response(
                        provider=f"Nebius Synthesis ({cand})",
                        status_code=200,
                        elapsed_ms=req_duration,
                        headers=resp.headers,
                        body=resp_json,
                        finish_reason=finish_reason,
                        usage=usage
                    )

                    if finish_reason == "length":
                        log_warning(f"Nebius synthesis hit max_tokens limit on candidate {cand}. Attempting next model...")
                        continue
                    if not content or not content.strip():
                        log_warning(f"Nebius synthesis returned empty content on candidate {cand}. Attempting next model...")
                        continue

                    cleaned_content = content.strip()
                    if cleaned_content.startswith("```json"):
                        cleaned_content = cleaned_content[7:]
                    elif cleaned_content.startswith("```"):
                        cleaned_content = cleaned_content[3:]
                    if cleaned_content.endswith("```"):
                        cleaned_content = cleaned_content[:-3]
                    cleaned_content = cleaned_content.strip()

                    try:
                        data = json.loads(cleaned_content)
                    except json.JSONDecodeError as jde:
                        log_warning(f"Decoding JSON synthesis error on candidate '{cand}': {jde}. Attempting next model...")
                        console.print(f"[dim yellow]Raw unparseable content preview (first 500 chars):[/dim yellow]\n{cleaned_content[:500]}")
                        continue

                    if _valid_synthesis(data):
                        data["model_used"] = cand
                        log_success(f"Evidence-grounded synthesis produced by Nebius ({cand}) in {req_duration:.0f}ms")
                        return data
                    log_warning(f"LLM synthesis on candidate {cand} failed validation checks. Attempting next candidate...")
                else:
                    log_http_response(
                        provider=f"Nebius Synthesis ({cand})",
                        status_code=resp.status_code,
                        elapsed_ms=req_duration,
                        headers=resp.headers,
                        body=resp.text
                    )
        except httpx.TimeoutException as toe:
            req_duration = (time.time() - req_start) * 1000
            if is_longtail:
                log_warning(f"Nebius synthesis timed out on long-tail model '{cand}' after {req_duration:.0f}ms.")
            else:
                log_warning(f"Nebius synthesis timed out after {req_duration:.0f}ms on {cand} (configured timeout: {int(timeout_sec)}s). Attempting next model...")
        except httpx.HTTPError as he:
            if is_longtail:
                log_warning(f"Nebius synthesis HTTP transport error on long-tail model '{cand}': {he}")
            else:
                log_warning(f"Nebius synthesis HTTP transport error on {cand}: {he}. Attempting next model...")
        except Exception as e:
            log_exception(e, f"Nebius synthesis unexpected exception on {cand}")

    log_warning("All LLM candidate synthesis models failed or timed out; falling back to deterministic clinical rules.")
    return None

@trace_call("main", log_args=False)
def main():
    args = parse_args()
    output_dir = resolve_output_dir(args.output_dir)

    log_step("Step 3 · Nebius Clinical Synthesis & Dosage Calculation", "Generate an evidence-based protocol and weight-based dose calculation")

    # Load patient from step 1 (run dir or central dir fallback)
    step1_file = output_dir / "01_orchestrator_result.json"
    if not step1_file.exists():
        step1_file = get_central_artifacts_dir() / "01_orchestrator_result.json"

    model_used = "zai-org/GLM-5.3-Flash"
    if step1_file.exists():
        with open(step1_file, "r", encoding="utf-8") as f:
            step1_data = json.load(f)
        patient = step1_data.get("patient", {})
        model_used = step1_data.get("model_used", model_used)
        log_info(f"Patient data loaded from Step 1 ({step1_file.name})")
    else:
        log_warning("01_orchestrator_result.json not found in the active paths, using fallback data.")
        patient = {"species": "Cat", "breed": "European Shorthair", "weight_kg": 4.0, "priority": "critical", "symptoms": "ingested cut flower"}

    # Load search docs from step 2 (run dir or central dir fallback)
    step2_file = output_dir / "02_tavily_search_result.json"
    if not step2_file.exists():
        step2_file = get_central_artifacts_dir() / "02_tavily_search_result.json"

    documents = []
    if step2_file.exists():
        with open(step2_file, "r", encoding="utf-8") as f:
            step2_data = json.load(f)
        documents = step2_data.get("documents", [])
        log_info(f"Search documents loaded from Step 2 ({len(documents)} references)")

    # Prefer evidence-grounded LLM synthesis; fall back to deterministic rules.
    synthesis = synthesize_with_llm(patient, documents, model_used, language=args.language)
    if synthesis:
        synthesis.setdefault("timestamp", time.strftime('%Y-%m-%d %H:%M:%S'))
        synthesis["patient"] = patient
        synthesis["synthesis_mode"] = "evidence_grounded_llm"
        synthesis["fallback"] = False
        if not synthesis.get("mandatory_sources"):
            synthesis["mandatory_sources"] = [
                {
                    "id": f"[{i + 1}]",
                    "source": d.get("source_name") or d.get("source_domain", "Veterinary source"),
                    "title": d.get("title", "Clinical reference"),
                    "url": d.get("url", ""),
                }
                for i, d in enumerate(documents[:5])
            ]
        log_info("Synthesis mode: [bold]Evidence-grounded LLM (Nebius)[/bold]")
    else:
        synthesis = build_clinical_synthesis(patient, documents)
        synthesis["synthesis_mode"] = "rule_based_fallback"
        synthesis["fallback"] = True
        synthesis["fallback_notice"] = FALLBACK_NOTICE
        # Loud, explicit alert in the Dagu logs — the model was not used.
        log_alert("RULE-BASED FALLBACK ENGAGED", FALLBACK_NOTICE)

    weight = float(patient.get("weight_kg", 4.0))

    log_metric("Presumptive Diagnosis", synthesis['presumptive_diagnosis'])
    proto = synthesis['immediate_intervention_protocol']
    log_info(f"Emesis induction: [bold]{proto['emesis_induction']['indication']}[/bold]")
    log_info(f"Activated charcoal: [bold]{proto['activated_charcoal']['indication']}[/bold]")
    log_info(f"Specific therapy: [bold]{proto['specific_antidote']['indication']}[/bold]")

    # Render formatted dosage table in terminal
    log_dosage_table(synthesis['dosage_calculation_table'], weight)

    # Save JSON Artifact
    save_artifact("03_clinical_synthesis.json", synthesis, output_dir)

    # Explicit banner when the AI model was unavailable and rules were used.
    fallback_banner = ""
    if synthesis.get("fallback"):
        fallback_banner = (
            "> # ⚠️ RULE-BASED FALLBACK — AI MODEL UNAVAILABLE\n"
            f"> **{FALLBACK_NOTICE}**\n\n"
        )

    # Generate Final Clinical Sheet Markdown Artifact
    sheet_md = f"""{fallback_banner}# 🚨 VETSENTINEL · EMERGENCY CLINICAL SHEET

- **Date & Time**: {synthesis['timestamp']}
- **Patient**: {patient.get('species')} ({patient.get('breed', 'N/A')}) · **{weight} kg**
- **Triage Code**: **{str(patient.get('priority', 'critical')).upper()}**
- **Presumptive Diagnosis**: **{synthesis['presumptive_diagnosis']}**
- **Intake Anamnesis**: {patient.get('symptoms', 'No anamnesis')}

---

## ⚡ IMMEDIATE INTERVENTION PROTOCOL

### 1. Emesis Induction: `{synthesis['immediate_intervention_protocol']['emesis_induction']['indication']}`
{synthesis['immediate_intervention_protocol']['emesis_induction']['details']}

### 2. Activated Charcoal: `{synthesis['immediate_intervention_protocol']['activated_charcoal']['indication']}`
{synthesis['immediate_intervention_protocol']['activated_charcoal']['details']}

### 3. Antidote / Specific Therapy: `{synthesis['immediate_intervention_protocol']['specific_antidote']['indication']}`
{synthesis['immediate_intervention_protocol']['specific_antidote']['details']}

---

## ⚖️ CALCULATED DOSAGE TABLE FOR {weight} KG

| Drug / Intervention | Standard Dosage | Patient Dose ({weight} kg) | Route | Formulation | Notes & Monitoring |
| :--- | :--- | :--- | :--- | :--- | :--- |
"""
    for d in synthesis['dosage_calculation_table']:
        sheet_md += f"| **{d['drug']}** | `{d['standard_dosage']}` | **{d['patient_dose']}** | `{d['route']}` | {d['formulation']} | {d['monitoring']} |\n"

    sheet_md += """
---

## 📚 MANDATORY SOURCE CITATIONS (EVIDENCE-BASED)
"""
    for s in synthesis['mandatory_sources']:
        sheet_md += f"- **{s['id']} {s['source']}**: *{s['title']}* - [{s['url']}]({s['url']})\n"

    sheet_md += "\n---\n*Clinical report generated automatically by the VetSentinel AI Triage Pipeline on the Dagu orchestrator.*\n"

    save_artifact("final_clinical_emergency_sheet.md", sheet_md, output_dir)

    # Generate _index.md artifact for instant preview in Dagu UI
    generate_run_index(
        target_dir=output_dir,
        patient=patient,
        model_name=model_used,
        files=[]
    )

    log_success("Step 3 completed successfully. Emergency sheet and artifact index stored.")

if __name__ == "__main__":
    try:
        main()
    except (KeyboardInterrupt, SystemExit):
        raise
    except Exception as e:
        log_exception(e, "Top-level Step 3 Clinical Synthesis execution")
        sys.exit(1)
